"""Transfers DB

Revision ID: 3b283144b8ef
Revises: eb9137d2a5b4
Create Date: 2019-05-01 18:13:06.464122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b283144b8ef'
down_revision = 'eb9137d2a5b4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cnpj', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('pagador_nome', sa.Text(), nullable=True),
    sa.Column('pagador_banco', sa.Text(), nullable=True),
    sa.Column('pagador_agencia', sa.Text(), nullable=True),
    sa.Column('pagador_conta', sa.Text(), nullable=True),
    sa.Column('beneficiario_nome', sa.Text(), nullable=True),
    sa.Column('beneficiario_banco', sa.Text(), nullable=True),
    sa.Column('beneficiario_agencia', sa.Text(), nullable=True),
    sa.Column('beneficiario_conta', sa.Text(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_transfers_client_id_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('client')
    # ### end Alembic commands ###
