"""Transfers DB

Revision ID: eb9137d2a5b4
Revises:
Create Date: 2019-05-01 16:09:33.062030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9137d2a5b4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cnpj', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    op.create_table('tranfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('pagador_nome', sa.Text(), nullable=True),
    sa.Column('pagador_banco', sa.Text(), nullable=True),
    sa.Column('pagador_agencia', sa.Text(), nullable=True),
    sa.Column('pagador_conta', sa.Text(), nullable=True),
    sa.Column('beneficiario_nome', sa.Text(), nullable=True),
    sa.Column('beneficiario_banco', sa.Text(), nullable=True),
    sa.Column('beneficiario_agencia', sa.Text(), nullable=True),
    sa.Column('beneficiario_conta', sa.Text(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_tranfers_client_id_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tranfers'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tranfers')
    op.drop_table('client')
    # ### end Alembic commands ###
